### ISSUE TITLE
Screen no contact result

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#103]

**Comment by djaiss** [comment]
![no search results](https://user-images.githubusercontent.com/61099/39413199-eee2f0ea-4bf4-11e8-8a99-ff1db1bc1f49.png)

**Comment by djaiss** [comment]
And the corresponding svg: https://send.firefox.com/download/2fbf753825/#DwbRCQLM4uhd_17GAoVrEQ

**Comment by Mokto** [comment]
Sorry the link has expired. Can you send it to me please ?

**Comment by Mokto** [comment]
@djaiss up

**Comment by Mokto** [comment]
Done via 2b7ca99575ab4796df6c93b27ef7ccfebe478b2e
