### ISSUE TITLE
[API] Fix calls issue

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#129]
<img width="876" alt="screen shot 2018-03-21 at 21 27 51" src="https://user-images.githubusercontent.com/5103928/37746385-69251f22-2d50-11e8-9494-378ed4973f70.png">
<img width="779" alt="screen shot 2018-03-21 at 21 27 59" src="https://user-images.githubusercontent.com/5103928/37746386-6941a8c2-2d50-11e8-9cce-6fcb11b879e3.png">

![screen shot 2018-03-21 at 21 28 26](https://user-images.githubusercontent.com/5103928/37746413-8286f6d4-2d50-11e8-9106-7a73b1695c53.png)

called_at attributes are wrong in the API call.

**Comment by djaiss** [comment]
The `called_at` field was in fact the `created_at` field.

**Comment by djaiss** [comment]
Pushed to staging.
