### ISSUE TITLE
Testers

### ISSUE THREAD

**Issue by Svarto** [monicahq/chandler#151]
Hi,

I just wanted to check if you need Android testers?

Happy to help once you feel it's ready for some testing.

**Comment by Mokto** [comment]
Hi @Svarto,

Thanks for your offer ! It is much appreciated.

We will launch the MVP soon, so you will be able to help us.
We have enabled a "Beta toggle" in the app allowing everyone to have/test the cutting edge features before it goes live for everyone.

**Comment by Svarto** [comment]
That sounds great, looking forward to helping out. Will it be launched through play store or is it something we sideload with an apk?

**Comment by Mokto** [comment]
It will be launched via the Google Play Store.

**Comment by Mokto** [comment]
@Svarto I am happy to tell you that the MVP is ready and will be launched in the Play store in the next few days. The IOS app has already been submitted.

Thanks !
