### ISSUE TITLE
RNDeviceInfo not working with version 0.40 

### ISSUE THREAD

**Issue by sfeu** [monicahq/chandler#154]
I get an undefined is not an abject error if the app tries to access getLocale on RNDeviceInfo. 

The new i18n of v0.4.0 seems to be broken at least with android.

I checked react-native link and it seems to be linked.

**Comment by Mokto** [comment]
This is weird.
This method should be available on Android.

This is becoming my priority (when I will be able to work on Chandler ;) )

Thanks for letting me know.

**Comment by Mokto** [comment]
I was quite busy this week but this is now fixed on 0.4.1.

Thanks !
