### ISSUE TITLE
0.4.1/android contact page

### ISSUE THREAD

**Issue by sfeu** [monicahq/chandler#165]
Above the section work information it shows a red box: "SegmentedControlIOS is not supported on this platform" .

The blue title bar displays "[object Object]"

**Comment by sfeu** [comment]
Works for me on android: #166

**Comment by Mokto** [comment]
Great. We still need to fix that [Object Object] issue though.

**Comment by Mokto** [comment]
Fixed in https://github.com/monicahq/chandler/pull/168
