### ISSUE TITLE
Android / get back button working

### ISSUE THREAD

**Issue by sfeu** [monicahq/chandler#167]
It would be great if we could get the android back button to work. Currently it closes the entire app, but it would be better if this would happen only on the main page.

**Comment by sfeu** [comment]
There is a back-handler for android that can be used to detect a back button press.

https://facebook.github.io/react-native/docs/backhandler.html

The expected behavior would be that it goes back all the steps till the main 
page and only from this page the application can be closed with the back button.

**Comment by Mokto** [comment]
This should be fixed via https://github.com/monicahq/chandler/commit/f2c2e21 (upgraded to react-navigation 2.0.0).

Thanks !
