### ISSUE TITLE
Contacts retrieval no longer works with new Monicahq 2.0.0 release

### ISSUE THREAD

**Issue by sfeu** [monicahq/chandler#174]
There was an API change that seems to prevent contact retrieval on 0.4.1

**Comment by djaiss** [comment]
@sfeu indeed, the API has changed but it shouldn't have affected the call.

Let me check.

**Comment by djaiss** [comment]
The API itself returns a contact when it's called.

@Mokto is this something on your side?

**Comment by Mokto** [comment]
@sfeu I seem be able to retrieve my contact list. @djaiss can you check on the latest build please ?

**Comment by sfeu** [comment]
I am using the docker version 2.0.0 from the docker hub and just tried with the most recent 0.4.2. The issue remains on my side and the contact list in the app remains empty. 

I am still suffering in setting up a debugging environment so that i can investigate myself.

**Comment by sfeu** [comment]
In seems that one needs to logout/login with the app after the server upgrade to 2.0.0 otherwise the contacts get not loaded  or displayed.

**Comment by Mokto** [comment]
Oh, ok ! Thanks for finding this @sfeu.

So I'll close the issue as we haven't launched the MVP yet.

**Comment by sfeu** [comment]
Ok sure!
