### ISSUE TITLE
Signin

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#2]
![signin](https://user-images.githubusercontent.com/5103928/34654524-db8015e6-f3ca-11e7-8c31-26f12fc4c796.png)

**Comment by djaiss** [comment]
@Mokto I've added a link to access the custom Monica's server URL field.

![signin](https://user-images.githubusercontent.com/61099/34967312-b8b75162-fa2f-11e7-95a7-59609bde2f5f.png)

This reloads the screen with a new field:

![signin](https://user-images.githubusercontent.com/61099/34967325-cb41f68e-fa2f-11e7-90d8-c166f4ac2826.png)

**Comment by Mokto** [comment]
We might need to add client_secret too.
