### ISSUE TITLE
wen login, I got this message: Bad credentials

### ISSUE THREAD

**Issue by westudiodev** [monicahq/chandler#208]
even if I had registered my account in pc website: https://app.monicahq.com
Wen I execute: npm run ios, the app launched , but get this message: Bad credentials wen I try to login
<img width="329" alt="screen shot 2018-05-18 at 14 24 10" src="https://user-images.githubusercontent.com/33219803/40219292-524915e0-5aa7-11e8-8b63-7754a8792c19.png">

**Comment by Mokto** [comment]
You are right !
This works on our staging environment.
I'll check ASAP.

**Comment by djaiss** [comment]
That should work now.

**Comment by Mokto** [comment]
Yes i confirm that ;)

**Comment by westudiodev** [comment]
yes, it can work now, thanks
