### ISSUE TITLE
oauth token to login change problems

### ISSUE THREAD

**Issue by sfeu** [monicahq/chandler#227]
with one of the recent versions there was this change from token to login.
I was not able to get this change working with 2.1.1. and got these type of server errors:

The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. {"exception":"[object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 3): The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. at /var/www/monica/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:82)
[stacktrace]
#0 /var/www/monica/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(178): League\\OAuth2\\Server\\Exception\\OAuthServerException::invalidRequest('client_id')

i changed back to 

 const resp = await this.api.post('/oauth/token', {
        body: {
          grant_type: 'password',
          client_id: '4',
          client_secret: 'xxxx',
          username: email,
          password,

and got it working again.

Maybe i missed some setting or require the most recent development head of monicahq?

**Comment by Mokto** [comment]
Hi  @sfeu,

I'm currently writing the documentation to help everybody make the app working with a custom server, but for the moment, you have to set the new MOBILE_CLIENT_ID and MOBILE_CLIENT_SECRET env variables on your  server.

**Comment by Mokto** [comment]
@sfeu is you issue resolved ?

**Comment by Mokto** [comment]
Closing this.

Feel free to continue the discussion in #239
