### ISSUE TITLE
self-hosted Monica using Docker - getting "bad credentials"

### ISSUE THREAD

**Issue by Svarto** [monicahq/chandler#239]
Hi,

Apologies but I am having some issues trying to connect through the mobile application to a self-hosted docker instance (using pure docker, not docker-compose or anything like that).

I can enter the running docker and generate the client secret and id by `docker exec -it monica sh` and then navigating to /var/www/monica to run the `php artisan passport:client --password`

Then I get the client ID and Secret and I add it into the .env passed to the docker, however, then when I try to connect to the Monica through Chandler app on Android I just have loading for a long time and then it says in red "bad credentials".

Nothing is shown in the logs on the monica instance, except for this:

[28/May/2018:20:45:24 +0000] "POST /oauth/login HTTP/1.1" 403 54 "-" "okhttp/3.6.0"

I am running Monica behind a reverse proxy, do you think this is giving me problems? I can access the monica instance just fine through the webbrowser, inside or outside my network...

**Comment by Mokto** [comment]
Hi @Svarto,

Is `./persist/storage:/var/www/monica/storage` a volume in your docker container ?
If those files get lost when you stop your docker container, your client credentials will be lost as well.

**Comment by NicholasBentley** [comment]
Interestingly enough, I'm getting something similar on a vanilla install using ubuntu.

**Comment by Svarto** [comment]
Hi @Mokto ,

I tried what you proposed and it didn't actually work, I still get the same error. I persist this volume through a bind mount into the container:

`/portainer/monica/storage:/var/www/monica/storage`

I then `docker exec -it monica sh` into the container and run the `php artisan passport:client --password` command, this created the client secret that I feed into the .env and I restart the docker container to load these Mobile Client ID and Secret.

Trying to connect with the mobile application still gives me a bad credentials error... I am at a loss, nothing in the logs except this: 

[29/May/2018:18:24:44 +0000] "POST /oauth/login HTTP/1.1" 403 54 "-" "okhttp/3.6.0"

**Comment by Mokto** [comment]
@djaiss @asbiin any idea ?

**Comment by djaiss** [comment]
It'll be interesting to debug.

@Svarto have you enabled logging? In your .env, you can set `APP_DEBUG=true`, `LOG_CHANNEL=syslog`, and you can even send errors to Sentry for instance (which has a free plan).

```
SENTRY_SUPPORT=true
SENTRY_DSN=YOUR KEY
```

What's bothering me is the fact that you have a long loading time. If it was purely an error on the instance itself, I think it would trigger the error immediately.

**Comment by Svarto** [comment]
Very strange, there are no debug or errors at all on the monica side. I have tried both LOG_CHANNEL=syslog or errorlog, nothing gets written...

The other piece is that when I added SENTRY the normal DSN gave me an error that it was incorrect, so I used and quoting here from sentry.io website: "DSN (Deprecated) that includes the secret which is no longer required by Sentry or newer versions of SDKs" - this avoids giving the error on monica boot however still no errors are posted at all.

What could help in this debug though is that the error message on the Chandler app changed now to "network request failed". When I get this error message in Chandler nothing shows up on the Monica server side. 

Another observation is that the php artisan passport:client --password are generating CLIENT_IDs that are always increasing, i.e. the first one I made was ID=1, now after debugging all the time I am up at ID=10 - can I somehow purge or see all the IDs I have generated? Can this create some problem having several passport:clients IDs generated?

Thanks a lot for your help here, really appreciate it.

**Comment by djaiss** [comment]
> Another observation is that the php artisan passport:client --password are generating CLIENT_IDs that are always increasing, i.e. the first one I made was ID=1, now after debugging all the time I am up at ID=10 - can I somehow purge or see all the IDs I have generated? Can this create some problem having several passport:clients IDs generated?

This doesn't have any consequences at all. You can have as many as you want, but if you want you can simply delete entries in the `oauth_clients` table in the database.

My guess would be that there is something between the app and Monica that prevents request from reaching the server. Unfortunately I have no skills whatsoever in proxies (or even Docker) to help here (and I feel stupid writing this down but that's the truth).

**Comment by Svarto** [comment]
No worries at all @djaiss , I am happy for any help and it has been super helpful to speak with you guys to try and narrow down the problem.

So it seems like the POST request is coming through, however, the duration is super long:

In my first reverse proxy:
`"POST /oauth/login HTTP/2.0" 403 54 "-" "okhttp/3.6.0" 41 "frontend1" "http://192.168.0.97:80" 130038ms`

and then it hits the second one, notice that HTTP changes from 2.0 in the first to 1.1 in the second:
`"POST /oauth/login HTTP/1.1" 403 54 "-" "okhttp/3.6.0" 1369 "Host-monica-server-com-0" "http://172.18.0.4:80" 130009ms`

It is odd that won't work with Monica app as I have several other apps that I can work using my self-hosted backends. I will try and fire up a container and install Monica the normal way, without docker, and see if that changes anything.

**Comment by spiveym** [comment]
Similar to OP but in this case for Heroku, I used the deployment button on the Monica Github page to set up my own instance of Monica. I also followed the additional instructions as noted to:

- run "php artisan passport:client --password"
- add the MOBILE_CLIENT_ID and MOBILE_CLIENT_SECRET to the Heroku config vars

Similarly, upon entry of my credentials and changing the server url to my personal instance, all I get back is "Bad Credentials". I enabled logging on the server but am not getting much back in terms of information aside from the returned 403 status

```
Jun 1 16:25:57 app[web] info xxx.xxx.xxx.xxx - - [01/Jun/2018:21:25:57 +0000] "POST /oauth/login HTTP/1.1" 403 65 "-" "Monica/23 CFNetwork/897.15 Darwin/17.5.0

Jun 1 16:25:57 heroku[router] info <158>1 2018-06-01T21:25:57.209932+00:00 host heroku router - at=info method=POST path="/oauth/login" host=xxx.herokuapp.com request_id=ae8931ee-37b2-4b5c-b991-2f31054e4fa2 fwd="xxx.xxx.xxx.xxx" dyno=web.1 connect=0ms service=168ms status=403 bytes=256 protocol=https
```

I have no problems logging into my monicahq.com account from iOS

**Comment by Drudoo** [comment]
Have the same problem using docker. 
The log just says: 

```
127.0.0.1 - - [02/Jun/2018:10:41:52 +0000] "POST /oauth/token HTTP/1.1" 500 1458 "-" "GuzzleHttp/6.3.3 curl/7.59.0 PHP/7.1.17"

xxx.xxx.xxx.xx - - [02/Jun/2018:10:41:52 +0000] "POST /oauth/login HTTP/1.1" 403 54 "-" "Monica/23 CFNetwork/897.15 Darwin/17.5.0"
```

**Comment by Svarto** [comment]
I set up an Ubuntu 16.04 instance and running Monica off that. While it still doesn't work, The positive news is that I get bad credential error on log-in instantly now when clicking sign-in I get an error:

```
LogicException: Key path "file:///home/svarto/monica/storage/oauth-private.key" does not exist or is not readable
  File "public/index.php", line 52
    $request = Illuminate\Http\Request::capture()
...
```

When I go to the /abovedir/storage/ I see no oauth-private.key at all in this folder, only other folders. Any ideas how to fix this?

**Comment by Svarto** [comment]
Ah, got it to work now, I had to run the following command:

`sudo php artisan passport:install` '

and then I checked the /monicadir/storage folder, seeing the two oauth files there, changed their ownership to my apache user (for me, www-data) and this made it all work.

I am not running Monica through the Docker anymore though, I am hosting it on a Ubuntu 16.04 VM.

**Comment by Drudoo** [comment]
@Svarto Thanks! 
I got it working by running `php artisan passport:install` inside my container.

**Comment by NicholasBentley** [comment]
Same! Thanks @Svarto

**Comment by dosch** [comment]
I have the same error on my debian/yunohost installation. 
Would you recommend running `php artisan passport:install` here as well?

**Comment by Svarto** [comment]
@dosch the importance is that the two key files are generated. I don't have experience with yunohost but if you can, check that the key files are generated and persistent in the folder location as mentioned above (adapted to your yunohost).

**Comment by dosch** [comment]
ok, did your steps, but I do not get this part:

> I then took the second generated key, called "Password grant client" and added it into the .env. 

What is "the .env"?

**Comment by Svarto** [comment]
@dosch this is the file with all your environmental variables (e.g. where you set your database parameters, the app url, if you allow new registration etc.)

It is placed (usually) in your Monica main directory, and as it is literally named .env at least in Debian the . in the beginning of the name means it is "hidden" so you need to do command "ls -a" to see it.

**Comment by anmol26s** [comment]
Hi
Is there a document for this. I have genrated the key with `php artisan passport:client --password`. Added the id and secret to **MOBILE_CLIENT_ID** and **MOBILE_CLIENT_SECRET** in **.env**. Generated new token from the app interface(which was quite long). Then tried on the app with my **email,token and url.** But there is error in red "bad credentials".

**Comment by Mokto** [comment]
@anmol26s I think you have to use your real password and not a custom generated token.

Docs are here : https://github.com/monicahq/monica/blob/master/docs/installation/mobile.md

**Comment by anmol26s** [comment]
Can we reopen this?

**Comment by croulibri** [comment]
Hello, same situation as @anmol26s 
I tested with the my user and real password but its not working still.
I am using YunoHost package (v 2.3.1) at https://github.com/YunoHost-Apps/monica_ynh and Android version 0.5.0 (latest on Playstore)
Thanks for giving us indication on how to succeed in connecting the Android App.

**Comment by Svarto** [comment]
Did you all check that the oauth key files got properly generates, have the correct file permissions and exists in your currently running Monica instancd?

**Comment by anmol26s** [comment]
@Svarto 
What permissions do you have for your keys?

**Comment by anmol26s** [comment]
I am getting 405 and 403 error : 
 ```
"GET /oauth/token HTTP/1.1" 405 31894 "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.1.18-1+0~20180611145904.18+stretch~1.gbp2b32f6"
"POST /oauth/login HTTP/1.1" 403 65 "-" "okhttp/3.6.0"
```

And on browser this page.
![monica_error](https://user-images.githubusercontent.com/5068843/42143119-23ab02dc-7dd1-11e8-88a5-a57b6f94875e.png)

**Comment by croulibri** [comment]
Hello,

With my Monica YunoHost package (v 2.3.1) at https://github.com/YunoHost-Apps/monica_ynh and Android version 0.5.0 (latest on Playstore), I did :

(1) `php artisan passport:client --password` => I got the two pair of ID and key and I reported the second ones called "Password grant client" into the .env

(2) and then I checked the /monica/storage folder, and the two required oauth files had been created, changed their ownership to my apache user and not root
```
cd /monicadir/storage
chown monica:monica oauth-private.key
chown monica:monica oauth-public.key
```
(2) I didn't find how to restart Monica so I did `artisan monica:update`

But the Android app still don't want to connect with my email and password of the web interface, I still get the `Bad Credential`

What did I miss ?

**Comment by timjrobinson** [comment]
Here are step by step instructions for those still confused (like I was):

Run `docker-compose run monicahq shell` from your monica directory to log into your monica docker container (run `docker-compose up -d` if it's not running yet)

Run `php artisan passport:install` once you're logged into the container. It will output something like the following:

```
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client Secret: ODHawLjUjiMo3FQdiVUoPhZ68doNm9OKSSFKWFBF
Password grant client created successfully.
Client ID: 2
Client Secret: 2p4cI8lJHuH5WrDsJyBY7qX7Be5Rv5Jhh2qmGVtB
```

Open the `.env` file in your monica directory in another terminal

At the bottom of this file add:

```
MOBILE_CLIENT_ID=2
MOBILE_CLIENT_SECRET=2p4cI8lJHuH5WrDsJyBY7qX7Be5Rv5Jhh2qmGVtB 
```

the secret is taken from the output before. 

Make sure that the APP_URL setting inside this `.env` file is correct. 

Restart monica with `docker-compose up -d`.

You should now be good to go.

**Comment by vongohren** [comment]
@timjrobinson what is the app url? It is said to be set to something, but it is never mentiond to what it is

**Comment by ckwalsh** [comment]
I just ran into this with an install on Ubuntu 18.04. I debugged it to a stale config cache - when I first started accessing my instance I didn't have the `.env` file set up properly, and the empty value was stored in `monica_root/bootstrap/cache/config.php`

It suddenly started working as soon as I ran `php artisan config:clear`

**Comment by napcae** [comment]
I'm running Monica in a docker container behind NGinx as a reverse proxy, my app logs says:

```
[2018-11-16 12:06:58] production.ERROR: Class 'Barryvdh\Debugbar\Facade' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Barryvdh\\Debugbar\\Facade' not found at /var/www/monica/app/Http/Controllers/Api/Auth/OAuthController.php:27)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\Api\\Auth\\OAuthController->login(Object(Illuminate\\Http\\Request))
#1 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#2 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)
#3 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\Auth\\OAuthController), 'login')
#4 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#5 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#6 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/monica/app/Http/Middleware/ThrottleRequestsMiddleware.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\ThrottleRequestsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 5, '1')
#9 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#13 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#14 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#15 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#16 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/monica/vendor/monicahq/laravel-cloudflare/src/Http/Middleware/TrustProxies.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Monicahq\\Cloudflare\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/monica/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/monica/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#35 /var/www/monica/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 {main}
"}
```

I followed @timjrobinson instructions. Let me know if I can help debug this thing

**Comment by gruzilla** [comment]
@timjrobinson thanks a lot for your summary! it is actually very important to take the second mobile ID, otherwise it does not work

@napcae had the same problem - you have to disable debugging, then it should work

**Comment by gruzilla** [comment]
@napcae i followed https://github.com/monicahq/chandler/issues/239#issuecomment-429189388 to the latter (uninstalled everything before trying this) and it worked - my problem was that i did not use the 2nd but the 1st mobile ID in the .env file..

did you check your permissions?

on the host:
```
$ ls -lan storage/
total 28
drwxrwxr-x 5 1000  101 4096 Nov 18 16:14 .
drwxrwxr-x 4 1000 1000 4096 Nov 18 17:12 ..
drwxrwxr-x 3 1000  101 4096 Nov 18 15:37 app
drwxrwxr-x 5 1000  101 4096 Nov 18 17:12 framework
drwxrwxr-x 2 1000  101 4096 Nov 18 15:43 logs
-rw-rw-r-- 1 1000  101 3292 Nov 18 16:14 oauth-private.key
-rw-rw-r-- 1 1000  101  812 Nov 18 16:14 oauth-public.key
```

inside the container:
```
$ docker exec -ti monicahq_monicahq_1 sh
/var/www/monica # ls -la storage
total 28
drwxrwxr-x    5 monica   apache        4096 Nov 18 15:14 .
drwxr-sr-x    1 monica   monica        4096 Nov 15 02:01 ..
drwxrwxr-x    3 monica   apache        4096 Nov 18 14:37 app
drwxrwxr-x    5 monica   apache        4096 Nov 18 16:12 framework
drwxrwxr-x    2 monica   apache        4096 Nov 18 14:43 logs
-rw-rw-r--    1 monica   apache        3292 Nov 18 15:14 oauth-private.key
-rw-rw-r--    1 monica   apache         812 Nov 18 15:14 oauth-public.key
```

also i have run `php artisan config:clear` and `php artisan cache:clear` before restarting the container.

i use https://hub.docker.com/r/jwilder/nginx-proxy/ as a reverse proxy.

**Comment by napcae** [comment]
Started from scratch got the same error.Permissions are correct and `php artisan config:clear` and `php artisan cache:clear` are run on the startup of the container anyway.
```
/var/www/monica/scripts/docker/waitfordb.sh
Connecting to mysql:3306
Waiting for database to settle ...
/var/www/monica/scripts/docker/test-server.sh
APP_KEY already set
✓ Maintenance mode: on
'/usr/bin/php7' 'artisan' down --message="Upgrading Monica v2.10.2" --retry="10"

✓ Resetting application cache
'/usr/bin/php7' 'artisan' cache:clear

✓ Clear config cache
'/usr/bin/php7' 'artisan' config:clear

✓ Resetting route cache
'/usr/bin/php7' 'artisan' route:cache

✓ Resetting view cache
'/usr/bin/php7' 'artisan' view:cache

✓ Performing migrations
'/usr/bin/php7' 'artisan' migrate --force

✓ Ping for new version
'/usr/bin/php7' 'artisan' monica:ping --force

✓ Cache configuraton
'/usr/bin/php7' 'artisan' config:cache

✓ Maintenance mode: off
'/usr/bin/php7' 'artisan' up

Monica v2.10.2 is set up, enjoy.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
172.19.0.1 - - [19/Nov/2018:12:49:15 +0000] "GET /oauth/token HTTP/1.1" 405 630 "-" "GuzzleHttp/6.3.3 curl/7.61.1 PHP/7.2.10"
172.19.0.1 - - [19/Nov/2018:12:49:14 +0000] "POST /oauth/login HTTP/1.1" 401 54 "-" "Monica/23 CFNetwork/975.0.3 Darwin/18.2.0"
```

Permissions:

```
root@twix /opt/monica # ls -la persist/storage/
total 28K
drwxrwxr-x 5 napcae uuidd 4.0K Nov 19 13:42 .
drwxr-xr-x 4 root   root  4.0K Nov 19 13:21 ..
drwxrwxr-x 3 napcae uuidd 4.0K Nov 19 13:21 app
drwxrwxr-x 5 napcae uuidd 4.0K Nov 19 13:43 framework
drwxrwxr-x 2 napcae uuidd 4.0K Nov 19 13:33 logs
-rw-rw-r-- 1 napcae uuidd 3.3K Nov 19 13:42 oauth-private.key
-rw-rw-r-- 1 napcae uuidd  812 Nov 19 13:42 oauth-public.key

root@twix /opt/monica # docker exec -it monica_monicahq_1 /bin/sh
/var/www/monica # ls storage/
app                logs               oauth-public.key
framework          oauth-private.key
/var/www/monica # ls -la storage/
total 28
drwxrwxr-x    5 monica   apache        4096 Nov 19 12:42 .
drwxr-sr-x   30 monica   monica        4096 Nov 19 12:43 ..
drwxrwxr-x    3 monica   apache        4096 Nov 19 12:21 app
drwxrwxr-x    5 monica   apache        4096 Nov 19 12:43 framework
drwxrwxr-x    2 monica   apache        4096 Nov 19 12:33 logs
-rw-rw-r--    1 monica   apache        3292 Nov 19 12:42 oauth-private.key
-rw-rw-r--    1 monica   apache         812 Nov 19 12:42 oauth-public.key
```

**Comment by vulcanjedi** [comment]
> @napcae i followed [#239 (comment)](https://github.com/monicahq/chandler/issues/239#issuecomment-429189388) to the latter (uninstalled everything before trying this) and it worked - my problem was that i did not use the 2nd but the 1st mobile ID in the .env file..
> 
> did you check your permissions?
> 
> on the host:
> 
> ```
> $ ls -lan storage/
> total 28
> drwxrwxr-x 5 1000  101 4096 Nov 18 16:14 .
> drwxrwxr-x 4 1000 1000 4096 Nov 18 17:12 ..
> drwxrwxr-x 3 1000  101 4096 Nov 18 15:37 app
> drwxrwxr-x 5 1000  101 4096 Nov 18 17:12 framework
> drwxrwxr-x 2 1000  101 4096 Nov 18 15:43 logs
> -rw-rw-r-- 1 1000  101 3292 Nov 18 16:14 oauth-private.key
> -rw-rw-r-- 1 1000  101  812 Nov 18 16:14 oauth-public.key
> ```
> inside the container:
> 
> ```
> $ docker exec -ti monicahq_monicahq_1 sh
> /var/www/monica # ls -la storage
> total 28
> drwxrwxr-x    5 monica   apache        4096 Nov 18 15:14 .
> drwxr-sr-x    1 monica   monica        4096 Nov 15 02:01 ..
> drwxrwxr-x    3 monica   apache        4096 Nov 18 14:37 app
> drwxrwxr-x    5 monica   apache        4096 Nov 18 16:12 framework
> drwxrwxr-x    2 monica   apache        4096 Nov 18 14:43 logs
> -rw-rw-r--    1 monica   apache        3292 Nov 18 15:14 oauth-private.key
> -rw-rw-r--    1 monica   apache         812 Nov 18 15:14 oauth-public.key
> ```
> also i have run `php artisan config:clear` and `php artisan cache:clear` before restarting the container.
> 
> i use https://hub.docker.com/r/jwilder/nginx-proxy/ as a reverse proxy.

Any insight on how to the get the jwilder proxy to work w/ this ?

**Comment by napcae** [comment]
What is your problem ? Which errors do you have? It’s not worth it to get the app running btw, it’s really minimal(and basically broken on iPhone X).

**Comment by vulcanjedi** [comment]
> What is your problem ? Which errors do you have? It’s not worth it to get the app running btw, it’s really minimal(and basically broken on iPhone X).

Chao Ban,

I haven't checked the errors I think I may have to do the custom .conf file.  I think this wouldn't be as helpful If I couldn't readily access from my phone. Which so happens to currently be an iPhoneX.  Its up. But I would prefer to have the proxy up. also think if this is cool my sister would find use in it and host for her w/o port forwarding...etc
