### ISSUE TITLE
Configuration option for TrustProxies

### ISSUE THREAD

**Issue by moritzsternemann** [monicahq/chandler#261]
First of all, thank you for your tireless efforts on the current and upcoming versions of Monica! ❤️ 

I found out about this development repo for the upcoming major version and wanted to try it out immediately. I spun up a similar setup to my existing self-hosted Monica instance and ran into the following issue:
The generated URLs in the Vue app, for example to JS assets, but also to links, use the http scheme instead of https. I use a reverse proxy in front of the docker container to terminates SSL and therefore, the browsers blocks loading of these generated non-https URLs. The `APP_URL` is set to `https://mydomain.tld` and I could resolve the asset case by setting `ASSET_URL` to the same value. However, links were still not working.

Finally, I tracked down what I believe to be the underlying issue: According to [the documentation of Ziggy](https://github.com/tighten/ziggy#tlsssl-termination-and-trusted-proxies), it takes Laravel's TrustProxies configuration into account and generates non-http URLs if no reverse proxy is detected.

I found that [the current version of Monica has a configuration option for this feature](https://github.com/monicahq/monica/blob/9b47c6b1dc093f44a2cae68b66d4a66128f2a780/app/Http/Middleware/TrustProxies.php#L16) but this version does not.

I'm happy to open a PR if you have the capacity for that right now. Else, feel free to close the issue if you think this should wait until later.

**Comment by asbiin** [comment]
Hi @moritzsternemann
Thank you for your kind feedbacks! We're trying to do our best ;)

About the proxy configuration: you're right, setting up this will fix your issue.
In this repo, you just have to set the `APP_TRUSTED_PROXIES` env variable (it's used [here](https://github.com/monicahq/chandler/blob/main/config/trustedproxy.php)). In a local environment, you can just set it to `*`:
```.env
APP_TRUSTED_PROXIES=*
```

@djaiss maybe we could add such a line in the `.env.example` file?

**Comment by djaiss** [comment]
@moritzsternemann thanks for your feedback. We are here only to serve the community 😄 

@asbiin is this a problem only when people run the instance locally, or do we have to do this change on the Docker image also? I don't think the Docker image is impacted since I've tried it and didn't have to mess with the config.

**Comment by djaiss** [comment]
@moritzsternemann @asbiin  can you check if this makes sense?

https://github.com/monicahq/chandler/pull/262

I don't know nothing about reverse proxies and anything infra... so you guys have to help me 😄

**Comment by asbiin** [comment]
@djaiss I guess you tried the docker image in http, apparently this is happening when using a reverse proxy to provide https support.

**Comment by moritzsternemann** [comment]
I just realized I never replied here and said thanks 🙈

I scrolled through the PHP files in `/config` but mostly looked at `app.php` and must've missed this one. When setting the correct environment variable, everything works as expected! Thank you! ❤️

**Comment by djaiss** [comment]
No problem @moritzsternemann Hope you like Chandler ;-)
