### ISSUE TITLE
BUG: Cannot login again after logging out

### ISSUE THREAD

**Issue by njelich** [monicahq/chandler#285]
After registering for an account, if I log out I cannot log back in, instead I get the following error.

<img width="953" alt="Screen Shot 2022-11-02 at 16 46 27" src="https://user-images.githubusercontent.com/12912633/199535675-d9026ff8-89c4-480a-912a-ccfacb6b24f9.png">

If I then go to register again using the same credentials it says the credentials are already taken.

<img width="622" alt="Screen Shot 2022-11-02 at 16 46 56" src="https://user-images.githubusercontent.com/12912633/199535792-8e9f4ba2-0811-4c94-8093-f9aba75d5f87.png">

**Comment by djaiss** [comment]
@njelich have you gone through the email verification process?

**Comment by njelich** [comment]
Yep, I discovered this when I logged out and tried to log back in.

**Comment by asbiin** [comment]
The login process is working well, so it might be something else...
What's you database backend?
Did you change your APP_KEY between registering and login?

**Comment by KierenConnell** [comment]
Can confirm I have the same issue with main docker image
`revision:a71b14ce977754d6df80d46a98ea5b36b6d46d1d`

On first account creation, I get email verification, login successfully, create vaults, contacts, etc.
Logout, attempt to log back in. Password is listed as incorrect.
Reset password successfully, can then log in and out repeatedly.

APP_KEY stays the same between registration and login.

Only time issue seems to occur is right after initial setup

I'm running latest version of mysql docker container

**Comment by asbiin** [comment]
OK I found the glitch, it's fixed now. Thank you @njelich and @KierenConnell for your help!
