### ISSUE TITLE
Import from monica classic?

### ISSUE THREAD

**Issue by Dalethium** [monicahq/chandler#326]
I was looking at this and it seems awesome! Will we be able to easily import from the original monica? And, is this ready for use? I'd love to get an instance up and running.

**Comment by djaiss** [comment]
Hi @Dalethium. We will be able to import data - eventually.
There are still some pieces missing to fully being to import data, activities and life events for instance, as well as gifts.

The `main` branch on Chandler is definitely ready for use and should be fairly stable. We might modify the migrations of the database until our proper v1 release, but it's stable enough for people to test it out, even if it's not yet feature complete.
