### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by njelich** [monicahq/chandler#328]
In the previous version, a major issue was cross platform compatibility and the extra work around efforts such as maintaining a mobile app - a crucial part of the experience.

PWAs have grown a lot as a concept, and there are loads of packages enabling easy conversion for Laravel based apps.

Are there any plans to go in that direction?

**Comment by djaiss** [comment]
We are building the API right now to be able to work on the mobile app right after. We plan to develop a proper mobile app this time, native and so on. I don't think we'll go through the PWA ourselves. However, if you or the community wants to make one, you are more than welcome to do so 😄

**Comment by njelich** [comment]
You might want to take a look at this - https://github.com/silviolleite/laravel-pwa

It's a really easy enable and I feel it's a much lighter effort than a full Native app. The feature parity is heck to keep up. A hybrid app like this is easier.
