### ISSUE TITLE
Prefix/suffix support

### ISSUE THREAD

**Issue by Laptop765** [monicahq/chandler#339]
I'm a new user and only briefly played around with `Monica` in part because of its lack of prefix/suffix support. I'm a Jr and so it was a blocker not to have my own name be correct. I set up `Chandler` via `Docker` and poked around all the options but this still seems to be missing. Is this a planned feature?

P.S. The new version is looking fantastic!

**Comment by djaiss** [comment]
This PR #348 will solve this.

**Comment by Laptop765** [comment]
Awesome, thank you so much!

**Comment by djaiss** [comment]
> Awesome, thank you so much!

welcome, thanks to you for the suggestion!
