### ISSUE TITLE
Nothing happens when trying to save contact information

### ISSUE THREAD

**Issue by Laptop765** [monicahq/chandler#343]
When trying to save, e.g. an e-mail address, clicking save does nothing. There doesn't seem to be any JS error nor request made to the server.

**Comment by djaiss** [comment]
> When trying to save, e.g. an e-mail address, clicking save does nothing. There doesn't seem to be any JS error nor request made to the server.

In the Contact information module?

**Comment by Laptop765** [comment]
Yes, this section. I should also note that I'm on `Safari` at the moment.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1468359/206932738-5212d8c8-d849-42b7-9bc0-32441f53a198.png">

**Comment by djaiss** [comment]
You are right... it works on chrome and firefox but not safari :-( Thanks for the bug report.

**Comment by Laptop765** [comment]
Yes I just confirmed that it works on Chrome as well.
