### ISSUE TITLE
Bad validation during login

### ISSUE THREAD

**Issue by DBX12** [monicahq/chandler#347]
There are some strange validations during the login, the regex `/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i` for example ignores TLDs like `.email` as it has more than four letters at the top-level-domain part. I will propose a pull request adapting the regex from `{2,4}` to `{2,}`

For another reason, my version of the app rejects `https://192.168.2.126` as valid domain. The regex seems to match it but the app still rejects it.

**Comment by DBX12** [comment]
Investigated it some more, it does accept my IP if I keep the `https://` part. I mean, if I delete everything from the server input, it turns to invalid and stays invalid even if I enter the full URL `https://192.168.2.126`. If I just delete the `app.monicahq.com` part of the URL (keeping the https://) and add my IP then, it works.
Seems like an internal issue of React Native.

**Comment by Mokto** [comment]
Hi @DBX12, sorry for the late reply but is it still happening ?
I'm on 0.7.0 and it is not the case anymore :

![output](https://user-images.githubusercontent.com/5103928/45725800-7d7c9e00-bb8a-11e8-8d11-a9811dd2ce7b.gif)

**Comment by DBX12** [comment]
Hmm, I have to trust your word on it, as I cheated myself around the issue (changed the mail in the database, logged in and changed it back to the original value)

**Comment by Mokto** [comment]
Ok, thanks !
