### ISSUE TITLE
Progressive Web App support

### ISSUE THREAD

**Issue by Laptop765** [monicahq/chandler#356]
On iOS you can add sites to the desktop in Safari. With proper support it will show up with the website's icon and open in its own window as if it were an app.

**Comment by Laptop765** [comment]
https://web.dev/learn/pwa/progressive-web-apps/ for more info. I realize this is probably low priority at the moment 🙂

**Comment by njelich** [comment]
Duplicate of:
https://github.com/monicahq/chandler/issues/328

**Comment by Laptop765** [comment]
Thanks for catching that!
