### ISSUE TITLE
Cannot login using MonicaHQ app

### ISSUE THREAD

**Issue by kennethpahn1** [monicahq/chandler#362]
I cannot log into my self-hosted MonicaHQ instance. No matter what I type in, it says "Bad Credentials"

**Comment by kennethpahn1** [comment]
Note: This is on iOS 11.4.1

**Comment by JC5** [comment]
Same thing for me. iOS 12 though. But I try works.

**Comment by JC5** [comment]
Sorry it works now. Had to generate keys. Apologies!

**Comment by Sup3rLativ3** [comment]
I've generated keys
I've updated .env with the key
I've updated the oauth files permissions
Restarted Apache

Rebooted the server. 

Still getting credentials error

**Comment by kennethpahn1** [comment]
Managed to resolve the issue by generating the keys using php too.
