### ISSUE TITLE
Cannot restore from SQL dump

### ISSUE THREAD

**Issue by kennethpahn1** [monicahq/chandler#363]
- Issue: Cannot restore from SQL dump due to 'modules' table having a field called 'key' which is a reserved word for MySQL. Changelog inside the SQL dump also causes issues too. SQL dump has issues with restoring the types of activities.
- Workaround is to rename the field to 'kay' (or anything other than key), and replace those fields in the SQL dump with 'kay' (or whatever you replaced the other field with), and then import that way. Remove changelog from SQL dump. No workaround for restoring types of activities except doing it normally.

**Comment by Mokto** [comment]
This issue should be referenced in the right repository : https://github.com/monicahq/monica
