### ISSUE TITLE
Design file?

### ISSUE THREAD

**Issue by njelich** [monicahq/chandler#364]
Is there any Figma or similar design file where we can collaborate on design choices?

**Comment by djaiss** [comment]
Unfortunately we have nothing like that.
We try to stick to what Tailwind provides us with most of the time, and we add some custom CSS here and there.
The idea is to have the least amount of custom CSS possible.

I'd say that if you want to change stuff, try to stick to Tailwind as much as possible, and also, submit a PR. Ideally, don't change things too much 🤭

**Comment by njelich** [comment]
I think that going forwards (once the prototype is done) a more proper approach to design would be useful, especially looping in an UI/UX designer.

**Comment by djaiss** [comment]
Definitely. However, as you know, it's a side project and we don't have employees :)
So a designer would have to be super motivated to work on a design library for an open source project.
