### ISSUE TITLE
Bug: Date type should be optional, but cannot be nulled

### ISSUE THREAD

**Issue by njelich** [monicahq/chandler#377]
![Screen Shot 2023-01-05 at 14 27 41](https://user-images.githubusercontent.com/12912633/210790804-caab4d3c-6743-4667-a271-8e24ed8655e9.png)

Also, the date type field variable is shared between the Create and the Edit modals. These elements should be abstracted better.

Path: Pages > Vault >Contact > ImportantDates > Index.vue

**Comment by djaiss** [comment]
🤦
You are right. Might not be the only place also.

**Comment by djaiss** [comment]
Thanks for the bug report!
