### ISSUE TITLE
Bug: Prefix is listed twice on the "Edit a Contact" page

### ISSUE THREAD

**Issue by Laptop765** [monicahq/chandler#393]
When editing a contact the `Suffix` field is labeled `Prefix`:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/1468359/211908729-251c4016-f6ad-4362-bb45-a059c1470b9b.png">

Browser: `Safari`

**Comment by djaiss** [comment]
Ouch. Fixing :-)

**Comment by djaiss** [comment]
#394 will fix it.
