### ISSUE TITLE
Bug: Unexpected behavior when clicking a name in autocomplete dropdown

### ISSUE THREAD

**Issue by Laptop765** [monicahq/chandler#395]
1. Go to `Add a relationship` for a contact
2. Select `Choose an existing contact`
3. Start typing the name of an existing contact
4. Click on the name to autocomplete

Expected: Select the name in the dropdown.

Actual: Navigates to that contact's page.

It seems the expectation is that users click the `Add` button next to the name but that wasn't immediately obvious. Navigating away from the page after clicking made me think that the operation was successful when it wasn't. I acknowledge this might be preference but wanted to call it out as unexpected.

Browser: `Safari`

**Comment by djaiss** [comment]
Thanks for the bug report. It's true that the behaviour is not ideal. I'll fix it.
