### ISSUE TITLE
[bug] "Mood tracking events" title is shown as "List of all important dates"

### ISSUE THREAD

**Issue by phorcys420** [monicahq/chandler#448]
## Summary
Version: [b27d282](https://github.com/monicahq/chandler/commit/b27d2820036f53365dff9510d1a2b176b4a1f035)

## Image
![image](https://user-images.githubusercontent.com/57866459/226618179-f2e8a254-f9e3-4edf-bcc9-cbb35a859481.png)

## How to reproduce
1. Go to reports tab
2. Click on "Mood tracking events"
3. Look at the "You are here" part of the UI

**Comment by djaiss** [comment]
Thanks a lot!
A pull request is on its way to fix this.
