### ISSUE TITLE
Invalid emojis in settings

### ISSUE THREAD

**Issue by phorcys420** [monicahq/chandler#456]
OS : Windows 10

---

![image](https://user-images.githubusercontent.com/57866459/228046666-68e978c9-df6c-426d-9c4e-c47e50b592b6.png)
![image](https://user-images.githubusercontent.com/57866459/228046730-dc481718-1c1b-496b-aa5f-8bc95ff669b3.png)

**Comment by djaiss** [comment]
Oh! I can fix that.
