### ISSUE TITLE
Inconsistency in "Personalize your contacts data" setting

### ISSUE THREAD

**Issue by phorcys420** [monicahq/chandler#457]
In settings, it's called "Personalize your contacts data"

![image](https://user-images.githubusercontent.com/57866459/228046887-1b0c0e72-98af-42a6-b586-c920a9ed5456.png)

---

But when you click on it, it's name is suddently "Personalize your account"
![image](https://user-images.githubusercontent.com/57866459/228046992-bdc03c71-edc1-4d87-8d4e-17a7f0d2fd12.png)

**Comment by djaiss** [comment]
You have a good eye. Thanks!
