### ISSUE TITLE
Allow for local file upload

### ISSUE THREAD

**Issue by phorcys420** [monicahq/chandler#460]
Currently, you can upload files and documents with Uploadcare.
My issue with Uploadcare is that you cannot self-host it.

I am very much paranoid about where my stuff goes, I would like it if we could keep the images locally.
This is a really big downside for me compared to OG Monica.

**Comment by tamaskan** [comment]
it's just temporary: https://github.com/monicahq/chandler/issues/346

**Comment by phorcys420** [comment]
oh okay sorry, thanks!
