### ISSUE TITLE
Signin on another Monica instance

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#47]
See https://github.com/monicahq/chandler/issues/2

**Comment by Mokto** [comment]
We should add a webview to prevent typing client_secret manually.

**Comment by sfeu** [comment]
I tried to change baseURI in api/index.ts but this seems to be not enough to connect to my own instance. Any idea how i can connect to my own instance as long as the webview still misses the own instance field?

**Comment by Mokto** [comment]
Hi @sfeu,

Did you change the client_id / client_secret ?

See here : https://github.com/monicahq/chandler/blob/develop/src/api/user.ts

**Comment by sfeu** [comment]
Thanks @Mokto,

I tried both, generating client_id/client_secret  via 
php artisan passport:client --password
and using the api settings page of monicahq but it always end up with a "bad credentials" msg and 
"POST /oauth/token HTTP/1.1" 500 8414 "-" "okhttp/3.6.0" on the server.

**Comment by Mokto** [comment]
@sfeu What is the server log message associated with the status 500 code error ?

**Comment by sfeu** [comment]
@Mokto I am sorry, but i could not figure out how to configure monica to be more communicative. I am using the docker image and have APP_DEBUG set to true and APP_LOG= syslog Unfortunately Laravel is kind of new to me and a  "grep -R log *" returns just a very few log statements that seem to be unrelated to auth.  

The "/oauth/token" seems to be part of the framework in my understanding. But there is no config/logging.php ?

**Comment by djaiss** [comment]
Personally I use `APP_LOG=daily` which creates an actual file in `storage/logs`, perhaps it's easier that way to debug.

**Comment by sfeu** [comment]
Thanks! I got:  Key path \"file:///var/www/monica/storage/oauth-private.key\" does not exist or is not readable at /var/www/monica/vendor/league/oauth2-server/src/CryptKey.php:45)

and figured out that i needed to run 

php artisan passport:install

which did the job and i finally can do a login with the app :)  Not sure if it is expected to be done or if monicahq should run this command when creating a new client via the settings?

Anyway, thanks for your support!

**Comment by djaiss** [comment]
The first time you set up your Monica instance, you need to run `php artisan passport:install` which will create 2 tokens that will be used to generate an Oauth client, needed for your app.

Yes it's complex for now, we'll try to be better in the future 😀

**Comment by sfeu** [comment]
@djaiss Could you open the wiki? I could try leave the hints there to help others get the app running on their own instance while you are working on the MVP.

**Comment by Mokto** [comment]
@sfeu Thanks ! The wiki was already open.

**Comment by dennistang** [comment]
It seems like the wiki redirects back to the repo's main page. Was hoping to find these instructions to point the MVP at my own instance. 😄

**Comment by Mokto** [comment]
@dennistang, I just merged this feature into develop.

You now have an url field when you log in on the app. Only thing needed server side is to [set client_id and client_secret env variables](https://github.com/monicahq/monica/blob/master/.env.example#L116).

Tell me if this does not work ;)

**Comment by Depau** [comment]
Hi,
I found this after trying to login from the official app (from Play Store) into my self hosted instance (docker). I ran `php artisan passport:client --password` in the container and updated `.env`, but it still says "bad credentials". Any hints?

**Comment by Mokto** [comment]
Hi @Depau,

What I did to make this work is to set `./persist/storage:/var/www/monica/storage` as a storage, because parts of the keys will be stored in `/var/www/monica/storage`.

Then you can regenerate you credentials, update `.env`, et re-run the `docker-compose up`.
