### ISSUE TITLE
"Create a contact entry for this person" is not readable in dark mode

### ISSUE THREAD

**Issue by vspaziani** [monicahq/chandler#493]
When adding another contact through an existing one while dark mode is enabled the check box text is not readable.
<img width="456" alt="Screenshot 2023-05-07 at 9 16 01 PM" src="https://user-images.githubusercontent.com/32283373/236726066-927b1144-be9e-46db-9d96-b3ba8f071c36.png">

**Comment by djaiss** [comment]
Thanks for letting us know.
