### ISSUE TITLE
[Design] Create a "Under construction" design

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#52]

**Comment by djaiss** [comment]
![under construction](https://user-images.githubusercontent.com/61099/35483813-81a7253c-0414-11e8-9709-3037513de74f.png)

And here are the asset in PNG and PNGx2. Do you need them in another format/resolution?


![groupx2](https://user-images.githubusercontent.com/61099/35483825-9fbae78e-0414-11e8-8836-186f458d6956.png)
![group](https://user-images.githubusercontent.com/61099/35483827-9fc9042c-0414-11e8-9136-a378e5c5e835.png)

**Comment by Mokto** [comment]
@djaiss  I need png@3x please

**Comment by djaiss** [comment]
Here we go.

![group](https://user-images.githubusercontent.com/61099/35834391-82a7755a-0aa3-11e8-9325-6ad8bdb78294.png)

**Comment by Mokto** [comment]
Done via https://github.com/monicahq/chandler/pull/66
