### ISSUE TITLE
Create an icon set

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#57]
Use [Icomoon or fontello](https://github.com/oblador/react-native-vector-icons#createiconsetfromfontelloconfig-fontfamily-fontfile) or any of [those](https://github.com/oblador/react-native-vector-icons#bundled-icon-sets)

Need :

- [x] Tabs
- [x] Contact activities

<img width="145" alt="screen shot 2018-01-31 at 20 21 54" src="https://user-images.githubusercontent.com/5103928/35656316-c7f5dd82-06c4-11e8-8937-cf9d45392359.png">

**Comment by djaiss** [comment]
Here is the Zip file containing the font chosen for the icons.

[fontello-c9ca926e.zip](https://github.com/monicahq/chandler/files/1697274/fontello-c9ca926e.zip)

Here is the legend

![image](https://user-images.githubusercontent.com/61099/35835481-fcc72fe2-0aa8-11e8-852d-619916d61396.png)

**Comment by Mokto** [comment]
@djaiss actually I'm not using Contact activities logos, I exported the original colorful logos via Sketch.

You can remove them from the icon set whenever you want (no hurry).

**Comment by Mokto** [comment]
Closed via d7a79f0e95c24a34fdcadc0c90f70e07b891d5f4
