### ISSUE TITLE
[API] Improve search request

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#79]
Needed : 
- [x] POST /contacts/search should become GET /contacts?query=
- [x] Should be able to specify limite and page
- [x] Should returns the total count of results in body.meta.total
- [x] Should return the asked query in body.query

**Comment by djaiss** [comment]
@Mokto Doc is here: https://www.monicahq.com/api/contacts#search

Note that 

> Should return the asked query in body.query

is actually `body.meta.query`.
