### ISSUE TITLE
Add statistics for activities and calls

### ISSUE THREAD

**Issue by Mokto** [monicahq/chandler#96]
- [x] Calls
- [x] Activities
- [ ] Activities : last 12 months

Example /contacts/{contactId}/calls?with=statistics

<img width="310" alt="screen shot 2018-02-23 at 20 07 10" src="https://user-images.githubusercontent.com/5103928/36623737-5eb78e9c-18d5-11e8-89cf-b5f084b72078.png">
Last 2 years
<img width="313" alt="screen shot 2018-02-23 at 20 07 15" src="https://user-images.githubusercontent.com/5103928/36623738-5ecf26ce-18d5-11e8-9560-0996c33f6fc4.png">
Last 2 years + last 12 months

**Comment by djaiss** [comment]
I didn't write the `with?` parameter. Instead, at the end of each api call, under `meta`, we now display 

![image](https://user-images.githubusercontent.com/61099/37877391-7daafffe-3028-11e8-8e9a-0feea40af346.png)

This is in staging.

**Comment by Mokto** [comment]
Nice !

@djaiss the last 12 months statistic is missing for activities. Should we remove the bar chart for the MVP ?

**Comment by Mokto** [comment]
Closing the issue as the 12 month barchart will be done after the MVP.

See https://github.com/monicahq/chandler/issues/147
